# Generated by Django 5.2.4 on 2025-07-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('battery_voltage', models.FloatField()),
                ('pitch', models.FloatField()),
                ('yaw', models.FloatField()),
                ('roll', models.FloatField()),
            ],
        ),
    ]
